name: wasteagram
description: CS492 - Project 5
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  cloud_firestore: ^3.4.3
  cupertino_icons: ^1.0.2
  firebase_analytics: ^9.3.0
  firebase_core: ^1.20.0
  firebase_storage: ^10.3.4
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^0.13.4
  image_picker: ^0.8.5+3
  google_fonts: ^3.0.1
  intl: ^0.17.0
  location: ^4.4.0
  path_provider: ^2.0.11
  sentry_flutter: ^6.9.0
  share: ^2.0.4
  shared_preferences: ^2.0.15
  sqflite: ^2.0.3
  url_launcher: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: 1.20.0
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

